sudo: required

cache:
  npm: false

services:
  - xvfb

# prevent travis from recursive gitsubmodule checkout
git:
  submodules: false

addons:
  firefox: "latest"


before_script:
  - git submodule update --init
  - npm install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 4
  - cd ref-mask
  - npm install
  - git submodule update --init
  - npm run build
  - cd ../
  - sleep 4
  - npm run build
  - npm run server &
  - sleep 7
  - firefox http://localhost:5777/utest/ &
  - sleep 8

script:
  - "npm test"

language: node_js

node_js:
  - 16
