before_script:
  - npm install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 4
  - cd ref-mask
  - npm install
  - git submodule init
  - git submodule update
  - npm run build
  - cd ../
  - sleep 4
  - npm run build &
  - npm run server &
  - sleep 4
  - firefox http://localhost:5777/utest/ &
  - sleep 4
 
script:
  - "npm test"
 
language: node_js