
compos-info:
	
	':scripts' :
		mode: 'server:all'
	
	':styles' :
		mode: 'server:all'
	
	':template':
		mode: server
	
	'layout:master':
		mode: server
		
	'layout:view' :
		mode: server
		
	':pageActivity' :
		mode: client
		
	':animation':
		mode: client
	