

include:
		
	routes:
		public : '/public/script/{0}.js' 
		public.compo: 'public/compo/{0}/{1}.js' 
		
		server : '/server/{0}.js' 
		lib : '/server/lib/{0}.js' 
		compo : '/server/compo/{0}/{1}.js'
		
		
	scripts:
		server:
			compo:
				- scripts
				- styles
		