


client:
	
	include:
		src: '/.reference/libjs/include/lib/include.js'
		
		
	scripts:
		atma:
			- ruqq/dom/jquery
			- class
			- mask
			- ruqq/ruqq.base
			- ruqq/utils
			- mask.node/mask.bootstrap
			- ruta
			- mask.animation
			
		public.compo:
			- pageActivity
		
	styles:
		- '/public/style/main.less'
		- '/public/compo/view/view.less'